---
version: '3.7'
services:
  elasticsearch_ecommerce_search_sample:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch_ecommerce_search_sample
    ports: [ '9200:9200' ]
    volumes:
      - ./es_data:/var/lib/elasticsearch/data
    environment:
      - node.name=elasticsearch_ecommerce_01
      - cluster.initial_master_nodes=elasticsearch_ecommerce_01
      - cluster.name=ecommerce_sample_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana_ecommerce_search_sample:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana_ecommerce_search_sample
    ports: [ '5601:5601' ]
    depends_on: [ 'elasticsearch_ecommerce_search_sample' ]
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch_ecommerce_search_sample:9200

  aerospike:
    image: aerospike/aerospike-server-enterprise:6.3.0.4
    container_name: aerospike_ecommerce_search_sample
    ports: [ '3000:3000' ]
    labels:
      com.aerospike.cluster: "ecommerce-app"
    volumes:
      - .:/etc/aerospike
      - "./aerospike.conf:/etc/aerospike/aerospike.conf"
      - "./features.conf:/etc/aerospike/features.conf"

  elasticsearch_outbound:
    image: aerospike/aerospike-elasticsearch-outbound:2.0.0
    container_name: aerospike_elasticsearch_outbound_ecommerce_search_sample
    ports: [ '8901:8901', '8902:8902' ]
    labels:
      com.aerospike.elasticsearch.outbound.cluster: "ecommerce-app"
    volumes:
      - ./aerospike-elasticsearch-outbound.yml:/etc/aerospike-elasticsearch-outbound/aerospike-elasticsearch-outbound.yml

# use docker volume to persist ES data outside a container.
volumes:
  es_data:
    driver: local
